framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed
        default_bus: message.bus
            
        buses:
            message.bus: ~
        
        transports:
            sync: 'sync://'
#            async: 'doctrine://default'
            # failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
            App\Messenger\Command\CalculatePaymentScheduleCommand: sync
            App\Messenger\Query\GetPaymentScheduleQuery: sync

#when@test:
#    framework:
#        messenger:
#            transports:
#                async: 'in-memory://'
