nelmio_api_doc:
    documentation:
        use_validation_groups: true
        info:
            title: PaymentSchedule API
            description: PaymentSchedule API
            version: 1.0.0
        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   BearerAuth: [ ]
    areas:
        path_patterns:
            - ^/api
            - ^/login
